name: flow8_recorder_v1
description: "Interfaccia Grafica Flow 8 - Test"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.1
  path_provider: ^2.1.2
  intl: ^0.19.0
  flutter_sound: ^9.15.0  # <--- Sostituisci record con questa
  url_launcher: ^6.2.5 # Aggiungi questa riga

  

flutter:

  uses-material-design: true







